rm(list=ls())
load("Table_2.bin")
group20=subset(data,Age<30)
group30=subset(data,data$Age <40 & data$Age>=30)
group40=subset(data,data$Age <50 & data$Age>=40)
group50=subset(data,data$Age <60 & data$Age >=50)
group60=subset(data,data$Age <70 & data$Age>=60)
group70=subset(data,data$Age >=70)
male=subset(data,Sex="Male")
female=subset(data,Sex="Female")

group=group40
median_act=median(na.omit(group$Vig_and_Moder))
std_act=sd(na.omit(group$Vig_and_Moder))
median_sensor=median(na.omit(group$Active))
std_sensor=sd(na.omit(group$Active))
median_steps=median(na.omit(group$Steps))
std_steps=sd(na.omit(group$Steps))
median_dist=median(na.omit(group$Meters))
std_dist=sd(na.omit(group$Meters))
median_sleep=median(na.omit(group$sleep_time))
std_sleep=sd(na.omit(group$sleep_time))
