rm(list=ls())
library(data.table)
data=data.frame(read.table("DataFreezeDataFrame_10022015.txt",header=T,sep='\t'))
#load('clusters.Rdata')
#names(cluster_df)=c("Subject","ActivityCluster")
#fractions=data.frame(read.table("fractions.updated.txt",header=T,sep='\t'))
#nontimeseries=data.frame(read.table("NonTimeSeries_10022015.txt",header=T,sep='\t'))
#m1=merge(nontimeseries,fractions,by.x="Subject",by.y="Subject",all.x=TRUE,all.y=FALSE)
#m2=merge(m1,cluster_df,by.x="Subject",by.y="Subject",all.x=TRUE,all.y=FALSE)
data$automotiveInstances=NULL
data$automotiveFraction48hrs=NULL
data$automotiveLongestGap=NULL
data$stationaryInstances=NULL
data$stationaryFraction48hrs=NULL
data$stationaryLongestGap=NULL
data$walkingInstances=NULL
data$walkingFraction48hrs=NULL
data$walkingLongestGap=NULL
data$runningInstances=NULL
data$runningFraction48hrs=NULL
data$runningLongestGap=NULL
data$unknownInstances=NULL
data$unknownLongestGap=NULL
data$unknownFraction48hrs=NULL 
data$cyclingInstances=NULL
data$cyclingLongestGap=NULL
data$cyclingFraction48hrs=NULL

write.csv(data,file="DataFreezeDataFrame_10022015_cleaned.txt",sep='\t')
