rm(list=ls())
library(data.table)
library(ggplot2)
data=data.frame(read.table("HeartAgeRelatedPredictions.txt",sep="\t",header=TRUE,row.names = 1))
agecor=round(cor(data$Age,data$HeartAge),2)
maintitle=paste("True Age vs Heart Age: R^2=",agecor,sep=" ")
plot(data$Age,data$HeartAge,xlab="True Subject Age",ylab="Predicted Heart Age",main=maintitle)
