library(data.table)
d_week=as.data.frame(read.table("weekday_subs_adjusted.txt",header=FALSE))
d_end=as.data.frame(read.table("weekend_subs_adjusted.txt",header=FALSE))
allvals=c(d_week$V2,d_end$V1)
mv=max(allvals) 
png('Substitutions.png')
par(mfrow=c(2,1))
barplot(d_week$V2, main="Weekday Unknown Substitutions",names.arg=d_week$V1,ylim=c(0,1))
barplot(d_end$V2, main="Weekend Unknown Substiutions",names.arg=d_end$V1,ylim=c(0,1))
dev.off()

